# fly.toml app configuration file generated for aygrade on 2026-01-17T11:02:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aygrade'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    VITE_API_URL = "https://aygrade-backend.fly.dev"
    VITE_STRIPE_PUBLISHABLE_KEY= "pk_live_51Sr3GPFqbEZQqsyFMFkUfepui8YCdQkdzJ1r7NMEAefIhYPKQ4sfnnCFNIyX9bxiT7BXo9xxeZtLrhVy1nZwNgmb00rix1shio"
    VITE_STRIPE_PRICING_TABLE_ID= "prctbl_1Sr4L2FqbEZQqsyFvmb2pcsZ"

[http_service]
  internal_port = 80
  force_https = true

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
