# fly.toml app configuration file generated for aygrade-backend on 2026-01-17T10:54:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aygrade-backend'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
